# Generated by Django 5.2.6 on 2025-09-23 15:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_status_event_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner friendly'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
